import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');
const specPath = path.join(projectRoot, 'src/libs/api/openapi/openapi.json');
const outputDir = path.join(projectRoot, 'src/libs/api/openapi/generated');
const schemaOutputPath = path.join(outputDir, 'schema.d.ts');
const clientOutputPath = path.join(outputDir, 'client.ts');

const primitiveMap = {
	string: 'string',
	boolean: 'boolean',
	integer: 'number',
	number: 'number',
};

function toPascalCase(value) {
	return value
		.replace(/[{}]/g, '')
		.split(/[^a-zA-Z0-9]+/)
		.filter(Boolean)
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join('');
}

function toCamelCase(value) {
	const pascal = toPascalCase(value);
	return pascal ? pascal.charAt(0).toLowerCase() + pascal.slice(1) : 'operation';
}

function escapeComment(value) {
	return String(value).replace(/\*\//g, '*\\/');
}

function dereferenceName(ref) {
	return ref.split('/').at(-1);
}

function resolveSchemaType(schema) {
	if (!schema) {
		return 'unknown';
	}

	if (schema.$ref) {
		return dereferenceName(schema.$ref);
	}

	if (Array.isArray(schema.enum) && schema.enum.length > 0) {
		return schema.enum.map((value) => JSON.stringify(value)).join(' | ');
	}

	if (Array.isArray(schema.type)) {
		return schema.type.map((type) => resolveSchemaType({ ...schema, type })).join(' | ');
	}

	if (schema.oneOf?.length) {
		return schema.oneOf.map((item) => resolveSchemaType(item)).join(' | ');
	}

	if (schema.anyOf?.length) {
		return schema.anyOf.map((item) => resolveSchemaType(item)).join(' | ');
	}

	if (schema.allOf?.length) {
		return schema.allOf.map((item) => resolveSchemaType(item)).join(' & ');
	}

	if (schema.type === 'array') {
		return `Array<${resolveSchemaType(schema.items)}>`;
	}

	if (schema.type === 'object' || schema.properties || schema.additionalProperties) {
		const properties = schema.properties ?? {};
		const required = new Set(schema.required ?? []);
		const entries = Object.entries(properties).map(([key, value]) => {
			const optional = required.has(key) ? '' : '?';
			return `${JSON.stringify(key)}${optional}: ${resolveSchemaType(value)};`;
		});

		if (schema.additionalProperties) {
			entries.push(`[key: string]: ${resolveSchemaType(schema.additionalProperties)};`);
		}

		return entries.length > 0 ? `{ ${entries.join(' ')} }` : 'Record<string, unknown>';
	}

	if (schema.type && primitiveMap[schema.type]) {
		return primitiveMap[schema.type];
	}

	return 'unknown';
}

function renderSchemaDeclarations(spec) {
	const schemas = spec.components?.schemas ?? {};
	const blocks = Object.entries(schemas).map(([name, schema]) => {
		const comment = schema.description ? `/** ${escapeComment(schema.description)} */\n` : '';
		return `${comment}export type ${name} = ${resolveSchemaType(schema)};`;
	});

	return `/* eslint-disable */
/* auto-generated by scripts/generate-openapi.mjs */

${blocks.join('\n\n')}
`;
}

function createOperationName(method, pathName) {
	const cleanedPath = pathName
		.split('/')
		.filter(Boolean)
		.map((segment) => (segment.startsWith('{') ? `by-${segment.slice(1, -1)}` : segment))
		.join('-');

	return toCamelCase(`${method}-${cleanedPath}`);
}

function getPrimarySuccessResponse(operation) {
	const responses = operation.responses ?? {};
	const successCode = Object.keys(responses)
		.filter((code) => /^2\d\d$/.test(code))
		.sort()[0];

	return successCode ? responses[successCode] : undefined;
}

function getResponseType(operation) {
	const response = getPrimarySuccessResponse(operation);
	const mediaTypes = response?.content ? Object.keys(response.content) : [];

	if (mediaTypes.length === 0) {
		return 'void';
	}

	const jsonLike =
		mediaTypes.find((type) => type.includes('json')) ??
		mediaTypes.find((type) => type === 'text/plain') ??
		mediaTypes[0];

	return resolveSchemaType(response.content?.[jsonLike]?.schema);
}

function getRequestBodyType(operation) {
	const content = operation.requestBody?.content ?? {};
	const mediaTypes = Object.keys(content);

	if (mediaTypes.length === 0) {
		return null;
	}

	const jsonLike =
		mediaTypes.find((type) => type.includes('json')) ??
		mediaTypes.find((type) => type === 'text/plain') ??
		mediaTypes[0];

	return resolveSchemaType(content[jsonLike]?.schema);
}

function collectParameterTypes(parameters = []) {
	const buckets = {
		pathParams: [],
		query: [],
		headers: [],
	};

	for (const parameter of parameters) {
		const target =
			parameter.in === 'path'
				? buckets.pathParams
				: parameter.in === 'query'
					? buckets.query
					: parameter.in === 'header'
						? buckets.headers
						: null;

		if (!target) {
			continue;
		}

		const optional = parameter.required ? '' : '?';
		target.push(`${JSON.stringify(parameter.name)}${optional}: ${resolveSchemaType(parameter.schema)};`);
	}

	return buckets;
}

function renderClient(spec) {
	const operationNames = [];
	const operationTypes = [];
	const methods = [];

	for (const [pathName, pathItem] of Object.entries(spec.paths ?? {})) {
		for (const [method, operation] of Object.entries(pathItem)) {
			const operationName = createOperationName(method, pathName);
			const responseType = getResponseType(operation);
			const requestBodyType = getRequestBodyType(operation);
			const parameterTypes = collectParameterTypes(operation.parameters);
			const summary = operation.summary || operation.description || `${method.toUpperCase()} ${pathName}`;

			operationNames.push(`\t${operationName}: ${JSON.stringify(pathName)},`);

			const parts = [];
			if (parameterTypes.pathParams.length > 0) {
				parts.push(`pathParams: { ${parameterTypes.pathParams.join(' ')} };`);
			}
			if (parameterTypes.query.length > 0) {
				parts.push(`query: { ${parameterTypes.query.join(' ')} };`);
			}
			if (parameterTypes.headers.length > 0) {
				parts.push(`headers: { ${parameterTypes.headers.join(' ')} };`);
			}
			if (requestBodyType) {
				parts.push(`body: ${requestBodyType};`);
			}
			parts.push(`response: ${responseType};`);

			operationTypes.push(`\t${operationName}: { ${parts.join(' ')} };`);

			const args = ['options: RequestOptions<ApiOperations[typeof operationName]> = {}'];
			const bodyInit =
				requestBodyType
					? `const body = options.body === undefined ? undefined : JSON.stringify(options.body);\n\n\t\t`
					: '';
			const contentTypeHeader = requestBodyType
				? `\n\t\t\t...(options.body === undefined ? {} : { 'content-type': 'application/json' }),`
				: '';

			methods.push(`\t/**
\t * ${escapeComment(summary)}
\t */
\tasync ${operationName}(options: RequestOptions<ApiOperations['${operationName}']> = {}): Promise<ApiOperations['${operationName}']['response']> {
\t\t${bodyInit}return this.request<ApiOperations['${operationName}']['response']>({
\t\t\tmethod: ${JSON.stringify(method.toUpperCase())},
\t\t\tpath: operationPaths.${operationName},
\t\t\tpathParams: options.pathParams,
\t\t\tquery: options.query,
\t\t\theaders: {${contentTypeHeader}
\t\t\t\t...options.headers,
\t\t\t},
\t\t\t${requestBodyType ? 'body,' : 'body: undefined,'}
\t\t});
\t}`);
		}
	}

	return `/* eslint-disable */
/* auto-generated by scripts/generate-openapi.mjs */
import type {
${Object.keys(spec.components?.schemas ?? {})
	.map((name) => `\t${name},`)
	.join('\n')}
} from './schema';

export const operationPaths = {
${operationNames.join('\n')}
} as const;

export type ApiOperations = {
${operationTypes.join('\n')}
};

type QueryValue = string | number | boolean | null | undefined;

export interface ClientConfig {
\tbaseUrl: string;
\tfetch?: typeof fetch;
\tgetHeaders?: () => HeadersInit | Promise<HeadersInit>;
}

export interface RequestOptions<T extends { response: unknown }> {
\tpathParams?: T extends { pathParams: infer TPathParams } ? TPathParams : never;
\tquery?: T extends { query: infer TQuery } ? TQuery : never;
\theaders?: T extends { headers: infer THeaders } ? THeaders : HeadersInit;
\tbody?: T extends { body: infer TBody } ? TBody : never;
\tsignal?: AbortSignal;
}

interface InternalRequestOptions {
\tmethod: string;
\tpath: string;
\tpathParams?: Record<string, string | number | boolean>;
\tquery?: Record<string, QueryValue>;
\theaders?: HeadersInit;
\tbody?: BodyInit | null;
\tsignal?: AbortSignal;
}

function buildPath(pathTemplate: string, pathParams?: Record<string, string | number | boolean>) {
\tif (!pathParams) {
\t\treturn pathTemplate;
\t}

\treturn pathTemplate.replace(/\\{([^}]+)\\}/g, (_, key) => encodeURIComponent(String(pathParams[key])));
}

function buildUrl(baseUrl: string, path: string, query?: Record<string, QueryValue>) {
\tconst normalizedBaseUrl = baseUrl.endsWith('/') ? baseUrl : \`\${baseUrl}/\`;
\tconst normalizedPath = path.startsWith('/') ? path.slice(1) : path;
\tconst url = new URL(normalizedPath, normalizedBaseUrl);

\tfor (const [key, value] of Object.entries(query ?? {})) {
\t\tif (value === undefined || value === null) {
\t\t\tcontinue;
\t\t}

\t\turl.searchParams.set(key, String(value));
\t}

\treturn url;
}

export class OpenApiClient {
\tprivate readonly baseUrl: string;
\tprivate readonly fetcher: typeof fetch;
\tprivate readonly getHeaders?: () => HeadersInit | Promise<HeadersInit>;

\tconstructor(config: ClientConfig) {
\t\tthis.baseUrl = config.baseUrl;
\t\tthis.fetcher = config.fetch ?? fetch;
\t\tthis.getHeaders = config.getHeaders;
\t}

\tprivate async request<T>({ method, path, pathParams, query, headers, body, signal }: InternalRequestOptions): Promise<T> {
\t\tconst url = buildUrl(this.baseUrl, buildPath(path, pathParams), query);
\t\tconst authHeaders = (await this.getHeaders?.()) ?? {};
\t\tconst response = await this.fetcher(url, {
\t\t\tmethod,
\t\t\theaders: {
\t\t\t\t...authHeaders,
\t\t\t\t...headers,
\t\t\t},
\t\t\tbody,
\t\t\tsignal,
\t\t\tcredentials: 'include',
\t\t});

\t\tif (!response.ok) {
\t\t\tconst text = await response.text();
\t\t\tthrow new Error(text || \`API request failed with status \${response.status}\`);
\t\t}

\t\tif (response.status === 204) {
\t\t\treturn undefined as T;
\t\t}

\t\tconst contentType = response.headers.get('content-type') ?? '';
\t\tif (contentType.includes('application/json')) {
\t\t\treturn (await response.json()) as T;
\t\t}

\t\treturn (await response.text()) as T;
\t}

${methods.join('\n\n')}
}
`;
}

async function main() {
	const rawSpec = await readFile(specPath, 'utf8');
	const spec = JSON.parse(rawSpec);

	await mkdir(outputDir, { recursive: true });
	await writeFile(schemaOutputPath, renderSchemaDeclarations(spec), 'utf8');
	await writeFile(clientOutputPath, renderClient(spec), 'utf8');

	console.log(`Generated OpenAPI artifacts:
- ${path.relative(projectRoot, schemaOutputPath)}
- ${path.relative(projectRoot, clientOutputPath)}`);
}

main().catch((error) => {
	console.error(error);
	process.exitCode = 1;
});
